app/urls.py
from django.urls import include, path

from . import views

urlpatterns = [
    # Accounts
    path('', views.home, name='home'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register', views.register, name='register'),

    # Events
    path('events/new', views.event_add_edit, name='event_new'),
    path('events/<int:pk>', views.event, name='event'),
    path('events/<int:pk>/edit', views.event_add_edit, name='event_edit'),
    path('events/<int:pk>/membership', views.event_membership, name='event_membership'),

    # Recipients
    path('events/<int:event_id>/recipients/<int:pk>', views.recipient, name='recipient'),

    # Ideas
    path('events/<int:event_id>/recipients/<int:recipient_id>/ideas/new', views.idea_add_edit, name='idea_new'),
    path('events/<int:event_id>/recipients/<int:recipient_id>/ideas/<int:pk>', views.idea, name='idea'),
    path('events/<int:event_id>/recipients/<int:recipient_id>/ideas/<int:pk>/edit', views.idea_add_edit, name='idea_edit'),

]

project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

app/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class User(AbstractUser):
    '''
    Extends AbstractUser, already has these fields
    username
    first_name
    last_name
    email
    password
    is_superuser()
    is_authenticated()
    '''
    pass

class Event(models.Model):
    title = models.CharField(max_length=100)
    exchange_date = models.DateField(auto_now=False, auto_now_add=False)
    organizer = models.ForeignKey(User, related_name="events", on_delete=models.CASCADE)
    members = models.ManyToManyField(User, related_name="memberships")
    # code
    # cover_image
    # is_public

    # Event Members
    '''
    - See a list of members (organizer can remove). If also recipient, recipient not deleted.
    - Option to invite a member by email. Clicking email auto joins group.
    - See a list of recipients. Some are members. Organizer can remove recipients.
    - If a member-recipient leaves a group, they will still be associated with the recipient in case they join again.
    - Organizer can add recipients, either from list of members, or create Non-Member list.
    '''

class Recipient(models.Model):
    name = models.CharField(max_length=50, blank=True, default="")
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    decider = models.ForeignKey(User, related_name="decisions", on_delete=models.SET_NULL, null=True)

    '''
    How does a recipient get added?
    - Admin can make a member that joined into a recipient.
    - Admin can invite a member to the group, making them a member or not.
    - Admin can create an external member 
    '''

class Idea(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField(blank=True, default='')
    recipient = models.ForeignKey(Recipient, related_name='ideas', on_delete=models.CASCADE)
    creator = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    # price = models.FloatField(default=0.0)
    # link = models.CharField(max_length=200, blank=True, default='')
    # likers = models.ManyToManyField(User, related_name='likes')
    # selected
    # image

'''

class Comment(models.Model):
    text
    user
    idea
    event? Meaning comments for the whole event, not specific to a certain idea
    pass

class Notification(model):
    read
    entity
    user
'''

'''
[NO] Anybody in the group can create a gift for anybody else in the group.
[NO] A recipient can be added twice to an event.
[YES] Many ideas can be added to a recipient, several can be selected for purchase.
[YES] A recipient can only have one decider.
[YES] Deciders must belong to the group.
[YES] Organizers assign deciders.
'''

app/templates/app/base.html
{% load static %}
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">
        <title>{% block title %}Gifty{% endblock title %}</title>

        <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">
        <script src="//cdn.jsdelivr.net/npm/sweetalert2@10"></script>
        <script src="sweetalert2.all.min.js"></script>
    </head>

    <style>
        body {
            font-family: Roboto, Sans-Serif;
        }
    </style>

    <body class="pb-5">
        <nav class="navbar navbar-light bg-light mb-4">
            <div class="container">
                <a class="navbar-brand" href="{% url 'home' %}">
                    <img class="mb-2" src="https://upload.wikimedia.org/wikipedia/commons/8/84/Gift_Flat_Icon_Vector.svg"/>
                    Gifty
                </a>
                <div>
                    {% if request.user.is_authenticated %}
                        {% if request.user.first_name %}
                            <span class="mr-3">Hello, {{request.user.first_name}}</span>
                        {% endif %}
                        <a href="{% url 'logout' %}">Logout</a>
                    {% else %}
                        <a href="{% url 'login' %}">Login</a>
                        <a href="{% url 'register' %}"> Register</a>
                    {% endif %}
                </div>
            </div>
        </nav>

        {% if messages %}
            <div class="toast-container position-absolute top-0 start-50 translate-middle-x p-3">
            {% for message in messages %}
                <div class="toast align-items-center text-white bg-{{message.tags}} border-0" role="alert" aria-live="assertive" aria-atomic="true">
                    <div class="d-flex">
                        <div class="toast-body">
                            {{ message }}
                        </div>
                        <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
                    </div>
                </div>
            {% endfor %}
            </div>
        {% endif %}

        <main id="main-content">
            <div class="container">
                {% block content %}Base page, override me.{% endblock %}
            </div>
        </main>

        {% block modal %}{% endblock modal %}

        {% block app %}{% endblock app %}

        <script defer>
            var toastElList = [].slice.call(document.querySelectorAll('.toast'));
            var toastList = toastElList.map(function (toastEl) {
                return new bootstrap.Toast(toastEl, {})
            });
            toastList.forEach(toast => toast.show());
        </script>
    </body>
</html>

app/templates/app/event.html
{% extends 'app/base.html' %}

{% block content %}
<div id="event">
    <div class="page-header">
        <a href="{% url 'home' %}">< All events</a>
        <div class="d-flex justify-content-between align-items-center">
            <div>
                <h1>{{event.title}}</h1>
                <div>{{event.exchange_date}}</div>
            </div>
            <div>
                <div>Members: [[message]]</div>
                {% for member in event.members.all %}
                    {% if member == event.organizer %}
                        <strong><div>{{member.username}}</div></strong>
                    {% else %}
                        <div>{{member.username}}</div>
                    {% endif %}
                {% endfor %}
                <button data-bs-toggle="modal" data-bs-target="#members-modal">Edit Members</button>
            </div>
            <div class="d-flex align-items-center">
                {% if event.organizer != request.user %}
                <a href="{% url 'event_membership' event.id %}">
                    {% if request.user in event.members.all %}Leave{% else %}Join{% endif %}
                </a>
                {% else %}
                    <form method="post" @submit.prevent="deleteEvent">
                        {% csrf_token %}
                        <input type="hidden" name="delete" value="delete">
                        <input type="submit" name="delete" class="btn btn-danger" value="Delete Event"/>
                    </form>
                    <a href="{% url 'event_edit' event.id %}" class="btn btn-primary m-2">Edit</a>
                {% endif %}
            </div>
        </div>
        <hr>
    </div>

    <h2>Recipients</h2>
    {% for recipient in event.recipient_set.all %}
    <a href="{% url 'recipient' event.id recipient.id %}">{{recipient.name}}</a>
    {% endfor %}
</div>


{% endblock content %}

{% block modal %}
    {% include 'modals/members.html' %}
{% endblock modal %}

{% block app %}
<script defer>
    var app = new Vue({
        el: '#event',
        delimiters: ['[[', ']]'],
        data: {
            message: 'Hello Vue'
        },
        methods: {
            deleteEvent(e) {
                Swal.fire({
                    title: 'Delete event',
                    text: 'Are you sure you want to delete this event? This action cannot be undone.',
                    icon: 'warning',
                    confirmButtonText: 'Delete',
                    showCancelButton: true,
                }).then(({isConfirmed}) => {
                    if (isConfirmed) {
                        e.target.submit();
                    }
                });
            },
        }
    });
</script>
{% endblock app %}

app/templates/app/event_add_edit.html
{% extends 'app/base.html' %}

{% block content %}

<div>Here is my event add edit page</div>

<form method="post">
{% csrf_token %}

{{form.as_p}}

<input type="submit" value="save">
</form>

{% endblock content %}

app/templates/app/home.html
{% extends 'app/base.html' %}

{% block content %}
<div class="d-flex justify-content-end">
    <a href="{% url 'event_new' %}" class="btn btn-primary">+ Create Event</a>
</div>

<div class="row gy-4 mb-5">
    {% for event in request.user.memberships.all %}
    <div class="col-4">
        <a href="{% url 'event' event.id %}">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">{{event.title}}</h5>
                    <h6 class="card-subtitle mb-2 text-muted">Exhange: {{event.exchange_date}}</h6>
                    {% comment %} <a href="{% url 'event_membership' event.id %}">Join</a> {% endcomment %}
                </div>
            </div>
        </a>
    </div>
    {% endfor %}
</div>

{% if events %}
<h3>Other Events</h3>
<div class="row gy-4">
    {% for event in events %}
    <div class="col-3">
        <a href="{% url 'event' event.id %}">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">{{event.title}}</h5>
                    <h6 class="card-subtitle mb-2 text-muted">{{event.exchange_date}}</h6>
                    {% if request.user.is_authenticated %}<a class="btn btn-primary" href="{% url 'event_membership' event.id %}">Join</a>{% endif %}
                </div>
            </div>
        </a>
    </div>
    {% endfor %}
</div>
{% endif %}


{% endblock content %}

app/templates/app/idea.html
{% extends 'app/base.html' %}

{% block content %}

<p>{{idea.title}}</p>
<p>{{idea.description}}</p>

{% endblock content %}

app/templates/app/idea_add_edit.html
{% extends 'app/base.html' %}

{% block content %}

<a href="{{back}}">Back</a>

<div>Here is my idea add edit page</div>

<form method="post">
{% csrf_token %}

{{form.as_p}}

<input type="submit" value="save">
</form>

{% endblock content %}

app/templates/app/recipient.html
{% extends 'app/base.html' %}

{% block content %}
<a href="{% url 'event' recipient.event_id %}"><- Back</a>
<h1>Gift Ideas for {{recipient.name}}</h1>

<a href="{% url 'idea_new' recipient.event_id recipient.id %}" class="btn btn-primary">Add Idea</a>

{% for idea in ideas %}
    <p>
        <a href="{% url 'idea' recipient.event_id recipient.id idea.id %}"><h5>{{idea.title}}</h5></a>
        <div>{{idea.description}}</div>
        {% if idea.creator_id == request.user_id or recipient.event.organizer_id == request.user_id %}
            <a href="{% url 'idea_edit' recipient.event_id recipient.id idea.id %}">Edit</a>
        {% endif %}
    </p>
{% endfor %}

{% endblock content %}